name: BuildImage

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Login to GitHub Packages Docker Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.pkg.github.com
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
      # -
      #   name: Build and Push
      #   run: |
      #     # ${{ secrets.GITHUB_TOKEN }}
      #     docker build -t docker.pkg.github.com/simulatan/docker-test/example .
      #     docker push docker.pkg.github.com/simulatan/docker-test/example
      -
        name: Restart over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: whoami